version: '3.8'

services:
  # PostgreSQL数据库
  postgres:
    image: docker.io/postgres:16-alpine
    container_name: edusched-postgres
    environment:
      POSTGRES_DB: edusched
      POSTGRES_USER: edusched
      POSTGRES_PASSWORD: edusched123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - edusched-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U edusched -d edusched"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis缓存和队列
  redis:
    image: docker.io/redis:7-alpine
    container_name: edusched-redis
    command: redis-server --appendonly yes --requirepass edusched123
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - edusched-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  edusched-network:
    driver: bridge